### ISSUE TITLE
Modularize the application.

### ISSUE THREAD

**Issue by dunderbruno** [dunderbruno/example#1]
Create Packages:

Domain
 - __ init __.py
 - user.py

Persistence
- __ init __.py
- userDAO.py

Make the relative imports if needed.

**Comment by asperduti** [comment]
Can I help you with this?

**Comment by dunderbruno** [comment]
Sure, feel free.

**Comment by asperduti** [comment]
OK, thanks.
Should packages name be Domain and Persistence?

**Comment by dunderbruno** [comment]
Yes.

**Comment by asperduti** [comment]
Hi @dunderbruno, I made the needed changes.

**Comment by dunderbruno** [comment]
Thanks!
